[package]
name = "polymorphicstubcreator"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = "0.6"
aes = "0.7.5"
block-modes = "0.8.1"
cipher = "0.3.0"
flate2 = "1.0"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"
windows-sys = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming"
]}
ratatui = "0.24"
crossterm = "0.27"
once_cell = "1.18"
humantime = "2.1"
rayon = "1.8"
tokio = { version = "1.0", features = ["full"] }
thread-control = "0.1.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
                                                                                                      
